- id: sqlalchemy-check-deferred-columns-before-drop
  name: Check for deferred columns before drop
  description: 'Linter for SQLAlchemy migrations'
  entry: check-deffered-columns
  language: python
  types: [text]
